"use client";
import { FormEvent, useState } from "react";
import { Camera, Save } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Avatar } from "@/components/ui/avatar";
import { ActionToast } from "@/components/forms/action-toast";
export function ProfileClient(){ const {user}=useAuth(); const [toast,setToast]=useState(""); const submit=(e:FormEvent)=>{e.preventDefault();setToast("Profile changes saved locally.");setTimeout(()=>setToast(""),2600)}; return <form onSubmit={submit} className="space-y-6"><div><h1 className="text-3xl font-black tracking-tight">Profile</h1><p className="mt-2 text-muted-foreground">Maintain your professional identity, account security, and notification preferences.</p></div><Card><CardHeader><div><CardTitle>Personal information</CardTitle><CardDescription>Visible to collaborators on projects, approvals, and messages.</CardDescription></div></CardHeader><div className="flex flex-col gap-6 md:flex-row"><div className="flex flex-col items-center gap-3"><Avatar name={user.name} className="h-24 w-24 text-xl"/><Button type="button" variant="outline"><Camera className="h-4 w-4"/>Change photo</Button></div><div className="grid flex-1 gap-4 md:grid-cols-2"><Input defaultValue={user.name} aria-label="Name"/><Input defaultValue={user.email} aria-label="Email"/><Input defaultValue={user.company} aria-label="Company"/><Input defaultValue={user.phone} aria-label="Phone"/><Input defaultValue={user.title} aria-label="Job title"/><Input defaultValue={user.address} aria-label="Address" className="md:col-span-2"/><Textarea defaultValue={user.bio} aria-label="Bio" className="md:col-span-2"/></div></div></Card><section className="grid gap-6 lg:grid-cols-2"><Card><CardTitle>Password update</CardTitle><CardDescription>Use a strong password with at least 8 characters.</CardDescription><div className="mt-5 space-y-3"><Input type="password" placeholder="Current password"/><Input type="password" placeholder="New password"/><Input type="password" placeholder="Confirm new password"/></div></Card><Card><CardTitle>Notification preferences</CardTitle><CardDescription>Choose how Groundbreak sends project updates.</CardDescription><div className="mt-5 space-y-3 text-sm font-semibold">{["Approval requests","Invoice payments","Blueprint comments","Offline sync alerts"].map(x=><label key={x} className="flex items-center justify-between rounded-2xl border p-4"><span>{x}</span><input type="checkbox" defaultChecked/></label>)}</div></Card></section><Button type="submit" variant="secondary"><Save className="h-4 w-4"/>Save changes</Button>{toast&&<ActionToast message={toast} onClose={()=>setToast("")}/>}</form>}
