"use client";
import { useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Edit3, Filter, LayoutGrid, List, Plus, Search, Trash2 } from "lucide-react";
import { tasks as seed } from "@/data/mock";
import { TaskItem } from "@/types";
import { Button } from "@/components/ui/button";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { ActionToast } from "@/components/forms/action-toast";

const statuses: TaskItem["status"][] = ["Pending", "In Progress", "Review", "Completed"];
const priorities: TaskItem["priority"][] = ["Low", "Medium", "High", "Critical"];
function tone(v:string){ return v==="Critical"?"red":v==="High"?"orange":v==="Completed"?"green":v==="Review"?"blue":"slate" as any; }

export function TasksClient(){
 const [items,setItems]=useState<TaskItem[]>(seed); const [view,setView]=useState<"kanban"|"table"|"calendar">("kanban"); const [q,setQ]=useState(""); const [priority,setPriority]=useState("All"); const [toast,setToast]=useState("");
 const filtered=useMemo(()=>items.filter(t=>(priority==="All"||t.priority===priority)&&[t.title,t.project,t.assignee].join(" ").toLowerCase().includes(q.toLowerCase())),[items,q,priority]);
 const create=()=>{ const next:TaskItem={id:`t${Date.now()}`, title:"New site coordination task", description:"Review field condition, assign owner, and update due date.", priority:"Medium", assignee:"Marcus Reed", dueDate:"2026-07-15", project:"Palm Residence", status:"Pending", progress:0, comments:[], attachments:[]}; setItems([next,...items]); setToast("Task created and added to Pending."); };
 const update=(id:string, patch:Partial<TaskItem>)=>{setItems(items.map(t=>t.id===id?{...t,...patch}:t)); setToast("Task updated.");};
 const remove=(id:string)=>{setItems(items.filter(t=>t.id!==id)); setToast("Task deleted.");};
 return <div className="space-y-6"><section className="rounded-[2rem] border bg-card p-6"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Badge tone="blue">Work management</Badge><h1 className="mt-3 text-4xl font-black tracking-tight">Tasks</h1><p className="mt-2 max-w-3xl text-muted-foreground">Plan, assign, filter, and complete field work across projects with Kanban, table, and calendar views.</p></div><div className="flex flex-wrap gap-2"><Button onClick={create} variant="secondary"><Plus className="h-4 w-4"/>Create task</Button><Button onClick={()=>setToast("Task filters saved as a reusable view.")} variant="outline"><Filter className="h-4 w-4"/>Save view</Button></div></div></section>
 <section className="flex flex-col gap-3 rounded-3xl border bg-card p-4 md:flex-row md:items-center"><div className="flex flex-1 items-center gap-2 rounded-2xl border bg-background px-3"><Search className="h-4 w-4 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search task, project, assignee..." className="border-0 bg-transparent shadow-none focus-visible:ring-0"/></div><select value={priority} onChange={e=>setPriority(e.target.value)} className="h-11 rounded-xl border bg-background px-3 text-sm"><option>All</option>{priorities.map(p=><option key={p}>{p}</option>)}</select><div className="grid grid-cols-3 gap-1 rounded-2xl border bg-background p-1">{[["kanban",LayoutGrid],["table",List],["calendar",CalendarDays]].map(([v,Icon]:any)=><button key={v} onClick={()=>setView(v)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${view===v?"bg-slate-950 text-white dark:bg-white dark:text-slate-950":"text-muted-foreground"}`}><Icon className="mx-auto h-4 w-4"/></button>)}</div></section>
 {view==="kanban"&&<div className="grid gap-4 xl:grid-cols-4">{statuses.map(s=><Card key={s} className="min-h-80"><CardHeader><div><CardTitle>{s}</CardTitle><CardDescription>{filtered.filter(t=>t.status===s).length} tasks</CardDescription></div></CardHeader><div className="space-y-3">{filtered.filter(t=>t.status===s).map(t=><article key={t.id} draggable className="rounded-2xl border bg-background p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-black">{t.title}</h3><Badge tone={tone(t.priority)}>{t.priority}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{t.project} · {t.assignee}</p><Progress className="mt-4" value={t.progress}/><p className="mt-2 text-xs text-muted-foreground">Due {t.dueDate} · {t.attachments.length} attachments</p><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>update(t.id,{status:"Completed",progress:100})}><CheckCircle2 className="h-4 w-4"/>Complete</Button><Button size="sm" variant="outline" onClick={()=>update(t.id,{status:s==="Pending"?"In Progress":"Review"})}><Edit3 className="h-4 w-4"/>Move</Button><Button size="sm" variant="ghost" onClick={()=>remove(t.id)}><Trash2 className="h-4 w-4"/></Button></div></article>)}</div></Card>)}</div>}
 {view==="table"&&<Card><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="text-left text-muted-foreground"><tr><th className="p-3">Task</th><th className="p-3">Project</th><th className="p-3">Assignee</th><th className="p-3">Priority</th><th className="p-3">Status</th><th className="p-3">Due</th><th className="p-3">Action</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-t"><td className="p-3 font-bold">{t.title}</td><td className="p-3">{t.project}</td><td className="p-3">{t.assignee}</td><td className="p-3"><Badge tone={tone(t.priority)}>{t.priority}</Badge></td><td className="p-3">{t.status}</td><td className="p-3">{t.dueDate}</td><td className="p-3"><Button size="sm" variant="outline" onClick={()=>update(t.id,{progress:Math.min(100,t.progress+10)})}>+10%</Button></td></tr>)}</tbody></table></div></Card>}
 {view==="calendar"&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(t=><Card key={t.id}><Badge tone={tone(t.priority)}>{t.priority}</Badge><h3 className="mt-4 text-xl font-black">{t.dueDate}</h3><p className="mt-2 font-semibold">{t.title}</p><p className="mt-2 text-sm text-muted-foreground">{t.project} · {t.status}</p><Textarea className="mt-4" defaultValue={t.comments.join("\n") || "Add field comment..."}/></Card>)}</div>}
 {toast&&<ActionToast message={toast} onClose={()=>setToast("")}/>}</div>;
}
